name: Build android apk package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

defaults:
  run:
    working-directory: .scripts/

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # 安装Flutter环境
      - name: Install Flutter
        uses: subosito/flutter-action@v2.16.0
        with:
          channel: 'stable'

      # 安装依赖
      - name: Install dependencies
        run: flutter pub get

      # 构建
      - name: Build apk
        run: flutter build apk

      # 上传到GitHub
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: apk
          path: build/app/outputs/flutter-apk/app-release.apk