name: Build installation files for Android and iOS

on:
  push:
    branches: [release, test]
  pull_request:
    branches: [release, test]

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 安装Flutter环境
      - name: Setup Flutter
        uses: subosito/flutter-action@v2.16.0
        with:
          channel: 'stable'

      # 安装依赖
      - name: Install dependencies
        run: flutter pub get

      # 准备环境
      - name : Setup Environment
        id: app
        run: .github/scripts/setup-runtime-environment.sh
        shell: bash

      # 为不同环境作构建
      - name: Build apk for test environment
        if: ${{ github.ref_name == 'test' }}
        run: flutter build appbundle -t lib/main_debug.dart --debug --dart-define=RELEASE_STORE=googleplay --no-tree-shake-icons

      - name: Build apk for release environment
        if: ${{ github.ref_name == 'release' }}
        run: flutter build appbundle --release --obfuscate --split-debug-info=build/obfuscating --dart-define=RELEASE_STORE=googleplay --no-tree-shake-icons

      # 上传到OSS
      - name: Upload to OSS
        uses: tvrcgo/oss-action@v1.0.0
        with:
          key-id: ${{ secrets.OSS_ACCESS_KEY_ID }}
          key-secret: ${{ secrets.OSS_ACCESS_KEY_SECRET }}
          region: oss-ap-southeast-1
          bucket: artifact-release
          assets: |
            build/app/outputs/bundle/release/app-*.aab:/${{ env.REPOSITORY_NAME }}/${{ github.ref_name }}/${{ steps.app.outputs.version_name }}/${{ env.GITHUB_SHA_SHORT }}.aab

#  build-ios:
#    runs-on: macos-latest
#    steps:
#      - uses: actions/checkout@v4
#      - name: Install Flutter
#        uses: subosito/flutter-action@v2.16.0
#        with:
#          channel: 'stable'
#      - name: Install dependencies
#        run: flutter pub get
#      - name: Build iOS ipa
#        run: flutter build ipa